spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: users_schema

server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
logging:
  level:
    org:
      flywaydb.core: debug
      springframework:
        security: debug
        web: debug

