spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: user
    password: user
server:
  port: 9000


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug

